# Generated by Django 5.1.4 on 2025-01-16 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WineCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='국가명(영문)')),
                ('name_kr', models.CharField(max_length=100, verbose_name='국가명(한글)')),
                ('is_common', models.BooleanField(default=False, verbose_name='주요 생산국')),
            ],
            options={
                'verbose_name': '와인 생산국',
                'verbose_name_plural': '와인 생산국 관리',
                'ordering': ['-is_common', 'name_kr'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TastingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100, verbose_name='와인 이름')),
                ('wine_type', models.CharField(choices=[('red', '레드'), ('white', '화이트'), ('sparkling', '스파클링'), ('rose', '로제'), ('champagne', '샴페인'), ('dessert', '디저트 와인'), ('fortified', '주정강화 와인'), ('orange', '오렌지와인'), ('natural', '내추럴 와인'), ('other', '기타')], max_length=20, verbose_name='와인 종류')),
                ('grape_varieties', models.CharField(blank=True, max_length=200, null=True, verbose_name='포도 품종')),
                ('vintage', models.IntegerField(blank=True, null=True, verbose_name='빈티지')),
                ('winery', models.CharField(blank=True, max_length=100, null=True, verbose_name='와이너리')),
                ('tasting_date', models.DateField(verbose_name='테이스팅 날짜')),
                ('tasting_place', models.CharField(default='Unknown', max_length=200, verbose_name='테이스팅 장소')),
                ('tasting_with', models.CharField(default='Unknown', max_length=200, verbose_name='테이스팅 대상')),
                ('tasting_pairing', models.CharField(default='Unknown', max_length=200, verbose_name='테이스팅 페어링')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='가격')),
                ('price_place', models.CharField(blank=True, max_length=200, null=True, verbose_name='구입처')),
                ('appearance_intensity', models.IntegerField(choices=[(1, '매우 연함'), (2, '연함'), (3, '보통'), (4, '진함'), (5, '매우 진함')], default=3, verbose_name='색의 강도')),
                ('appearance_clarity', models.CharField(choices=[('clear', '맑음'), ('hazy', '흐림'), ('cloudy', '탁함')], default='clear', max_length=50, verbose_name='투명도')),
                ('appearance_color', models.CharField(choices=[('purple', 'Purple'), ('ruby', 'Ruby'), ('garnet', 'Garnet'), ('tawny', 'Tawny'), ('brown', 'Brown'), ('deep_red', 'Deep Red'), ('lemon', 'Lemon'), ('gold', 'Gold'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink'), ('apricot', 'Apricot'), ('strawberry', 'Strawberry'), ('coral', 'Coral'), ('gold', 'Gold'), ('white', 'White'), ('orange', 'Orange')], default='purple', max_length=50, verbose_name='색상')),
                ('aroma_type', models.CharField(choices=[('apple', '사과'), ('pear', '배'), ('peach', '복숭아'), ('plum', '자두'), ('cherry', '체리'), ('berry', '베리'), ('citrus', '시트러스'), ('stone_fruit', '과육'), ('tropical_fruit', '열대과일'), ('pineapple', '파인애플'), ('banana', '바나나'), ('mango', '망고'), ('papaya', '파파야'), ('rose', '장미'), ('lilac', '라일락'), ('violet', '바이올렛'), ('iris', '아이리스'), ('jasmine', '자스민'), ('lavender', '라벤더'), ('peony', '포아니'), ('daisy', '데이지'), ('vanilla', '바닐라'), ('coffee', '커피'), ('chocolate', '초콜릿'), ('herbal', '허브'), ('herb', '허브'), ('oak', '오크'), ('cedar', '세이드'), ('vanilla', '바닐라'), ('coffee', '커피'), ('chocolate', '초콜릿'), ('herbal', '허브'), ('almond', '아몬드'), ('peanut', '땅콩'), ('walnut', '호두'), ('hazelnut', '헤이즐넛'), ('pecan', '페칸'), ('pistachio', '피스타치오'), ('leather', '가죽'), ('chocolate', '초콜릿')], default='apple', max_length=50, verbose_name='아로마 타입')),
                ('taste_sweetness', models.IntegerField(choices=[(1, '매우 드라이'), (2, '드라이'), (3, '중간'), (4, '스위트'), (5, '매우 스위트')], default=3, verbose_name='당도')),
                ('taste_acidity', models.IntegerField(choices=[(1, '매우 낮음'), (2, '낮음'), (3, '중간'), (4, '높음'), (5, '매우 높음')], default=3, verbose_name='산도')),
                ('taste_tannin', models.IntegerField(choices=[(1, '매우 부드러움'), (2, '부드러움'), (3, '중간'), (4, '강함'), (5, '매우 강함')], default=3, verbose_name='탄닌')),
                ('taste_body', models.IntegerField(choices=[(1, '매우 가벼움'), (2, '가벼움'), (3, '중간'), (4, '무거움'), (5, '매우 무거움')], default=3, verbose_name='바디')),
                ('rating', models.IntegerField(choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], default=3, verbose_name='평점')),
                ('overall', models.TextField(verbose_name='종합 평가')),
                ('is_public', models.BooleanField(default=False, verbose_name='공개 여부')),
                ('image', models.ImageField(blank=True, null=True, upload_to='tasting_notes/', verbose_name='이미지')),
                ('aroma_notes', models.JSONField(default=list)),
                ('taste_notes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_tasting_notes', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasting_notes', to='notes.winecountry', verbose_name='생산국')),
            ],
            options={
                'verbose_name': '테이스팅 노트',
                'verbose_name_plural': '테이스팅 노트들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TastingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasting_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasting_events', to='notes.tastingnote')),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='와인 이름')),
                ('winery', models.CharField(max_length=200, verbose_name='와이너리')),
                ('vintage', models.CharField(blank=True, max_length=4, verbose_name='빈티지')),
                ('wine_type', models.CharField(choices=[('red', '레드'), ('white', '화이트'), ('sparkling', '스파클링'), ('rose', '로제'), ('champagne', '샴페인'), ('dessert', '디저트 와인'), ('fortified', '주정강화 와인'), ('orange', '오렌지와인'), ('natural', '내추럴 와인'), ('other', '기타')], max_length=50, verbose_name='와인 종류')),
                ('region', models.CharField(max_length=200, verbose_name='생산지역')),
                ('grapes', models.JSONField(default=list, verbose_name='포도 품종')),
            ],
            options={
                'verbose_name': '와인',
                'verbose_name_plural': '와인들',
                'indexes': [models.Index(fields=['name'], name='notes_wine_name_d9cc73_idx'), models.Index(fields=['winery'], name='notes_wine_winery_5092e4_idx')],
            },
        ),
    ]
