# Generated by Django 5.1.4 on 2025-01-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingnote',
            name='aroma_intensity',
            field=models.IntegerField(choices=[(1, '매우 약함'), (2, '약함'), (3, '중간'), (4, '강함'), (5, '매우 강함')], default=3, verbose_name='아로마 강도'),
        ),
    ]
