# Generated by Django 5.1.4 on 2025-01-16 19:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_tastingnote_aroma_intensity'),
    ]

    operations = [
        migrations.AddField(
            model_name='tastingevent',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='테이스팅 날짜'),
            preserve_default=False,
        ),
    ]
